### PR TITLE
Include ways to access Network Link Conditioner after installation

### PR DESCRIPTION
**Pull request by denismullaraj**
Provided information on how to access Network Link Conditioner either via Spotlight Search or via the System Preferences.

### CODE REVIEW

**Comment by mattt** [comment]
Thanks for your PR, @denismullaraj. While it's helpful to know that Spotlight provides a convenient way to access preference panes, I don't think this is particularly relevant to this article.

**Comment by mattt** [comment]
Actually, it looks like I misunderstood the point of your PR. I'm sorry about that, @denismullaraj.

I just tried to install this for the first time on a new machine (macOS 10.14.4). The first time you install and open from System Preferences, it works as expected. But quit and reopen System Preferences, and the preference pane is now gone; attempting to reinstall the preference pane results in the following error: 

> **You can’t install the “Network Link Conditioner” preferences.**
> “Network Link Conditioner” preferences is installed with macOS and can’t be replaced.

This is a regression from previous versions of macOS, and is indeed something that should be documented in this article. I'll have to take another look at what's going on and the best way to mitigate this.

**Comment by denismullaraj** [comment]
> Actually, it looks like I misunderstood the point of your PR. I'm sorry about that, @denismullaraj.
> 
> I just tried to install this for the first time on a new machine (macOS 10.14.4). The first time you install and open from System Preferences, it works as expected. But quit and reopen System Preferences, and the preference pane is now gone; attempting to reinstall the preference pane results in the following error:
> 
> > **You can’t install the “Network Link Conditioner” preferences.**
> > “Network Link Conditioner” preferences is installed with macOS and can’t be replaced.
> 
> This is a regression from previous versions of macOS, and is indeed something that should be documented in this article. I'll have to take another look at what's going on and the best way to mitigate this.

Exactly! You can only open and find the Network Link Conditioner only by searching in Spotlight Search. If the user would like to open again the Network Link Conditioner from the System Preferences the extra step about moving it to the public directory from the terminal it is required. After that the preference pane Network Link Conditioner will always show in the System Preferences :) Hope it helps! As when I installed it, it wasn't obvious and I was expecting it to show up in the System Preferences after the installation. So moving it to the public folder as I stated with that terminal command, made it work as expected after installation.

**Comment by mattt** [comment]
> If the user would like to open again the Network Link Conditioner from the System Preferences the extra step about moving it to the public directory from the terminal it is required. 

I think this is the correct workaround for the regression. I'm just about to update to macOS 10.14.6; I'll check again to see if that fixes anything.

**Comment by mattt** [comment]
Just updated the article. See the callout under ["Installation"](https://nshipster.com/network-link-conditioner/#installation)

**Comment by denismullaraj** [comment]
> Just updated the article. See the callout under ["Installation"](https://nshipster.com/network-link-conditioner/#installation)

Sounds great! I guess now it's perfect and "macOS 10.14"-fool :)

**Pull request closed without merging**
