### PR TITLE
Add missing decimal point in number formatter example

### PR DESCRIPTION
**Pull request by ianbytchek**

### CODE REVIEW

**Comment by mattt** [comment]
Thanks for this, @ianbytchek. Much appreciated!

**Comment by ianbytchek** [comment]
@mattt I got it all wrong and rushed with this without testing it first. The code was correct, please reset to the previous commit or I can make another PR. 🤦‍♂️ SORRY!

**Comment by mattt** [comment]
Well if it makes you feel any better, that makes two of us. Unfolding the rest of the context, I now remember what this example was demonstrating, and can confirm that it was originally correct. Reverted with #733.

**Comment by mattt** [comment]
Thanks for following up on that, @ianbytchek.

**Pull request merged**
