### PR TITLE
Add Sync to Core Data Synchronizers

### PR DESCRIPTION
**Pull request by 3lvis**
Adds [Sync](https://github.com/hyperoslo/Sync).

### CODE REVIEW

**Comment by 3lvis** [comment]
Any update on this? :smile:

**Comment by rickytan** [comment]
这个怎么处理吗？@croath

**Comment by croath** [comment]
@rickytan It's up to Nate. If it's gonna be merged into master, we'll also update the translation version.

**Comment by natecook1000** [comment]
Thanks, @3lvis—I'm working on a larger update to that article to bring it current. Sync will be included when that goes up.

**Comment by 3lvis** [comment]
@natecook1000 Thanks, you are fantastic. :)

**Pull request closed without merging**
