### PR TITLE
Added Swift translations to 2013-09-23-ios7.md

### PR DESCRIPTION
**Pull request by 0x7fffffff**
First time contributing to NSHipster articles. Please let me know if I need to change anything.

### CODE REVIEW

**Comment by natecook1000** [comment]
Awesome, @0x7fffffff! I'll review and get these up soon—thanks so much! :clap: :clap: :clap:

**Comment by croath** [comment]
It will be a little bit surprise seeing Swift in an article introducing iOS 7 :tada:

**Comment by 0x7fffffff** [comment]
@natecook1000 Glad to help! Once again let me know if there's anything I should change. I'd love to do more of these in the future.

**Comment by 0x7fffffff** [comment]
@croath I had that thought as well, but I figured the Swift versions might be worth having since they work with iOS 7 APIs.

**Comment by natecook1000** [comment]
Thanks so much for these, @0x7fffffff! :tada: :dizzy:

**Pull request merged**
