### PR TITLE
I think there was an extra let name there?

### PR DESCRIPTION
**Pull request by philosopherdog**

### CODE REVIEW

**Comment by natecook1000** [comment]
Thanks for noticing that, @philosopherdog, but that's intentional—it unwraps the optional `NSString` within the loop.

**Comment by philosopherdog** [comment]
Ok. Is it in the loop's block though? What you have there doesn't compile.

**Comment by natecook1000** [comment]
It isn't in the block, it's a part of the `while` statement. Since `scanUpToCharactersFromSet` returns a `Bool`, that loop is basically:

```
while condition, let name = name {
    // ...
}
```

I'll take another look though, it clearly isn't very readable!

**Comment by natecook1000** [comment]
@philosopherdog, I tried this out and it *is* failing. As you said—sorry about that! The rules for shadowing a variable name must have changed since Swift 1.2, and this expression no longer works. Thanks for letting me know! I'll go back and update the rest of the article for Swift's current incarnation, as well.

**Pull request merged**
